#!/bin/sh
#
#PBS -N QC_data2
#PBS -o logs/QC_data2.log
#PBS -e logs/QC_data2.err
#PBS -q batch
#PBS -l nodes=1:ppn=4
#PBS -l walltime=48:00:00

source /home/qukun/minghaofang/miniconda3/etc/profile.d/conda.sh
conda activate ecc_pipe

cd /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
python3 ecc_pipe_master.py --QC -n 4 --config /home/qukun/minghaofang/workspace/project/ecc/paper_data_final/script/config/QC_config_data_02.yaml


