#!/bin/sh
#
#PBS -N Circle-DNA_1_sup
#PBS -o logs/Circle-DNA_sup.log
#PBS -e logs/Circle-DNA_sup.err
#PBS -q fat
#PBS -l nodes=1:ppn=18
#PBS -l walltime=96:00:00

source /home/qukun/minghaofang/miniconda3/etc/profile.d/conda.sh
conda activate ecc_pipe

cd /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
python3 ecc_pipe_master.py --Detect --tool AA -n 18 --config /home/qukun/minghaofang/workspace/project/ecc/paper_data_final/script/config/AA_config_1.yaml


