#!/bin/sh
#
#PBS -N cresil
#PBS -o logs/cresil.log
#PBS -e logs/cresil.err
#PBS -q batch
#PBS -l nodes=1:ppn=12
#PBS -l walltime=48:00:00

source /home/qukun/minghaofang/miniconda3/etc/profile.d/conda.sh
conda activate ecc_pipe

cd /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
python3 ecc_pipe_master.py --Detect --tool cresil -n 12 --config /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe/config/cresil_config_test.yaml

