#!/bin/sh
#
#PBS -N Circle-DNA_3
#PBS -o logs/Circle-DNA_3.log
#PBS -e logs/Circle-DNA_3.err
#PBS -q fat
#PBS -l nodes=1:ppn=36
#PBS -l walltime=96:00:00

source /home/qukun/minghaofang/miniconda3/etc/profile.d/conda.sh
conda activate ecc_pipe

cd /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
python3 ecc_pipe_master.py --Detect --tool circlemap -n 36 --config //home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/script/config/circlemap_config_3.yaml


