#!/bin/sh
#
#PBS -N Circle-DNA_2
#PBS -o logs/Circle-DNA_2.log
#PBS -e logs/Circle-DNA_2.err
#PBS -q fat
#PBS -l nodes=1:ppn=24
#PBS -l walltime=48:00:00

source /home/qukun/minghaofang/miniconda3/etc/profile.d/conda.sh
conda activate ecc_pipe

cd /home/qukun/minghaofang/workspace/project/ecc/pipe/ecc_pipe
python3 ecc_pipe_master.py --Detect --tool circlemap -n 24 --config /home/qukun/minghaofang/workspace/project/ecc/bib_revised/paper_data/MB_data/script/config/circlemap_config_2.yaml


